export type Region = {
  state: string;
  district: string;
  tehsils: string[];
};

export const HP_REGIONS: Region[] = [
  {
    state: "Himachal Pradesh",
    district: "Bilaspur",
    tehsils: [
      "Bharari",
      "Bilaspur Sadar",
      "Ghumarwin",
      "Jhanduta",
      "Kalol",
      "Naina Devi",
      "Namhol",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Chamba",
    tehsils: [
      "Bhalai",
      "Bharmour",
      "Bhattiyat",
      "Chamba",
      "Churah",
      "Dalhousie",
      "Dharwala",
      "Holi",
      "Kakira",
      "Pangi",
      "Pukhri",
      "Saho",
      "Saluni",
      "Sihunta",
      "Telka",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Hamirpur",
    tehsils: [
      "Barsar",
      "Bhoranj",
      "Bhota",
      "Dhatwal",
      "Galore",
      "Hamirpur",
      "Jahu",
      "Kangoo",
      "Lambloo",
      "Nadaun",
      "Tauni Devi Bamson",
      "Tira Sujanpur",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Kangra",
    tehsils: [
      "Alampur",
      "Baijnath",
      "Baroh",
      "Bharoli",
      "Bhawarna",
      "Chadiyar",
      "Dadasiba",
      "Dareeni",
      "Dehra Gopipur",
      "Dharamshala",
      "Dhira",
      "Fatehpur",
      "Gangath",
      "Harchakian",
      "Haripur",
      "Indora",
      "Jaisinghpur",
      "Jaswan",
      "Jawalamukhi",
      "Jawali",
      "Kangra",
      "Khundian",
      "Kotla",
      "Lagru",
      "Majheen",
      "Multhan",
      "Nagrota Bagwan",
      "Nagrota Surian",
      "Nurpur",
      "Palampur",
      "Panchrukhi",
      "Pragpur",
      "Raja Ka Talab",
      "Rakkar",
      "Rey",
      "Sadwan",
      "Shahpur",
      "Sulah",
      "Thakurdwara",
      "Thural",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Kinnaur",
    tehsils: [
      "Hangrang",
      "Kalpa",
      "Moorang",
      "Nichar",
      "Poo",
      "Sangla",
      "Tapri",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Kullu",
    tehsils: [
      "Anni",
      "Banjar",
      "Bhuntar",
      "Jari",
      "Kullu",
      "Manali",
      "Nirmand",
      "Nither",
      "Sainj",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Lahaul and Spiti",
    tehsils: [
      "Lahaul",
      "Spiti",
      "Udaipur",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Mandi",
    tehsils: [
      "Aut",
      "Bagachnogi",
      "Bagshad",
      "Baldwara",
      "Balh",
      "Bali Chowki",
      "Bhadrota",
      "Chachyot",
      "Chhatri",
      "Dehar",
      "Dhalwan",
      "Dharmpur",
      "Jogindarnagar",
      "Karsog",
      "Katoula",
      "Kotli",
      "Lad Bharol",
      "Makridi",
      "Mandap",
      "Mandi",
      "Nihri",
      "Padhar",
      "Pangna",
      "Rewalsar",
      "Sandhol",
      "Sarkaghat",
      "Sundarnagar",
      "Thachi",
      "Thunag",
      "Tihra",
      "Tikken",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Shimla",
    tehsils: [
      "Chaupal",
      "Chirgaon",
      "Deha",
      "Dhami",
      "Dodra Kwar",
      "Jalog",
      "Jangla",
      "Jubbal",
      "Junga",
      "Kalbog",
      "Kotgarh",
      "Kotkhai",
      "Kumarsain",
      "Kupvi",
      "Nankhari",
      "Nerwa",
      "Rampur",
      "Rohru",
      "Sarahan",
      "Sarawati Nagar",
      "Shimla Rural",
      "Shimla Urban",
      "Sunni",
      "Taklech",
      "Theog",
      "Tikar",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Sirmaur",
    tehsils: [
      "Dadahu",
      "Haripurdhar",
      "Kamrau",
      "Majra",
      "Nahan",
      "Narag",
      "Nohra",
      "Pachhad",
      "Pajhota",
      "Paonta Sahib",
      "Rajgarh",
      "Renuka",
      "Ronhat",
      "Shillai",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Solan",
    tehsils: [
      "Arki",
      "Baddi",
      "Darlaghat",
      "Kandaghat",
      "Kasauli",
      "Krishangarh",
      "Kunihar",
      "Loharghat",
      "Mamlig",
      "Nalagarh",
      "Panjehra",
      "Parwanoo",
      "Ramshahr",
      "Solan",
    ],
  },
  {
    state: "Himachal Pradesh",
    district: "Una",
    tehsils: [
      "Amb",
      "Bangana",
      "Bharwain",
      "Birhu Kalan",
      "Dulahar",
      "Gagret",
      "Ghanari",
      "Haroli",
      "Ispur",
      "Jol",
      "Mehatpur",
      "Una",
    ],
  },
];

export const DEFAULT_STATE = "Himachal Pradesh";

export function getStates(): string[] {
  return Array.from(new Set(HP_REGIONS.map((region) => region.state))).sort();
}

export function getDistricts(state: string = DEFAULT_STATE): string[] {
  return HP_REGIONS.filter((region) => region.state === state)
    .map((region) => region.district)
    .sort();
}

export function getTehsilsForDistrict(district: string): string[] {
  return HP_REGIONS.find((region) => region.district === district)?.tehsils ?? [];
}

export const LOCATION_TYPE_OPTIONS = [
  { value: "mc", label: "Municipal Corporation / Municipal Council" },
  { value: "tcp", label: "Town & Country Planning / SADA / Nagar Panchayat Area" },
  { value: "gp", label: "Gram Panchayat" },
];
