-- District staff default credentials (generated from seed_data/district-staff-accounts.csv)
-- Role | District | Mobile | Username | Default Password | Email
-- Dealing Assistant | Chamba HQ | 7800001001 | da_chamba | dacha@2025 | da.chamba@himachaltourism.gov.in
-- District Tourism Officer | Chamba HQ | 7900001001 | dtdo_chamba | dtdocha@2025 | dtdo.chamba@himachaltourism.gov.in
-- Dealing Assistant | Bharmour Sub-Division | 7800001002 | da_bharmour | dabha@2025 | da.bharmour@himachaltourism.gov.in
-- District Tourism Officer | Bharmour Sub-Division | 7900001002 | dtdo_bharmour | dtdobha@2025 | dtdo.bharmour@himachaltourism.gov.in
-- Dealing Assistant | Shimla HQ (AC Tourism) | 7800001003 | da_shimla_hq | dashi@2025 | da.shimla-hq@himachaltourism.gov.in
-- District Tourism Officer | Shimla HQ (AC Tourism) | 7900001003 | dtdo_shimla_hq | dtdoshi@2025 | dtdo.shimla-hq@himachaltourism.gov.in
-- Dealing Assistant | Hamirpur (serving Una) | 7800001004 | da_hamirpur | daham@2025 | da.hamirpur@himachaltourism.gov.in
-- District Tourism Officer | Hamirpur (serving Una) | 7900001004 | dtdo_hamirpur | dtdoham@2025 | dtdo.hamirpur@himachaltourism.gov.in
-- Dealing Assistant | Kullu (Bhuntar/Manali) | 7800001005 | da_kullu_manali | dakul@2025 | da.kullu-manali@himachaltourism.gov.in
-- District Tourism Officer | Kullu (Bhuntar/Manali) | 7900001005 | dtdo_kullu_manali | dtdokul@2025 | dtdo.kullu-manali@himachaltourism.gov.in
-- Dealing Assistant | Kullu Dhalpur | 7800001006 | da_kullu_dhalpur | dakul@2025 | da.kullu-dhalpur@himachaltourism.gov.in
-- District Tourism Officer | Kullu Dhalpur | 7900001006 | dtdo_kullu_dhalpur | dtdokul@2025 | dtdo.kullu-dhalpur@himachaltourism.gov.in
-- Dealing Assistant | Dharamsala (Kangra) | 7800001007 | da_dharamsala | dadha@2025 | da.dharamsala@himachaltourism.gov.in
-- District Tourism Officer | Dharamsala (Kangra) | 7900001007 | dtdo_dharamsala | dtdodha@2025 | dtdo.dharamsala@himachaltourism.gov.in
-- Dealing Assistant | Kinnaur (Reckong Peo) | 7800001008 | da_kinnaur | dakin@2025 | da.kinnaur@himachaltourism.gov.in
-- District Tourism Officer | Kinnaur (Reckong Peo) | 7900001008 | dtdo_kinnaur | dtdokin@2025 | dtdo.kinnaur@himachaltourism.gov.in
-- Dealing Assistant | Kaza (Spiti ITDP) | 7800001009 | da_kaza | dakaz@2025 | da.kaza@himachaltourism.gov.in
-- District Tourism Officer | Kaza (Spiti ITDP) | 7900001009 | dtdo_kaza | dtdokaz@2025 | dtdo.kaza@himachaltourism.gov.in
-- Dealing Assistant | Lahaul (Keylong) | 7800001010 | da_lahaul | dalah@2025 | da.lahaul@himachaltourism.gov.in
-- District Tourism Officer | Lahaul (Keylong) | 7900001010 | dtdo_lahaul | dtdolah@2025 | dtdo.lahaul@himachaltourism.gov.in
-- Dealing Assistant | Mandi Division | 7800001011 | da_mandi | daman@2025 | da.mandi@himachaltourism.gov.in
-- District Tourism Officer | Mandi Division | 7900001011 | dtdo_mandi | dtdoman@2025 | dtdo.mandi@himachaltourism.gov.in
-- Dealing Assistant | Pangi (ITDP) | 7800001012 | da_pangi | dapan@2025 | da.pangi@himachaltourism.gov.in
-- District Tourism Officer | Pangi (ITDP) | 7900001012 | dtdo_pangi | dtdopan@2025 | dtdo.pangi@himachaltourism.gov.in
-- Dealing Assistant | Shimla Division | 7800001013 | da_shimla | dashi@2025 | da.shimla@himachaltourism.gov.in
-- District Tourism Officer | Shimla Division | 7900001013 | dtdo_shimla | dtdoshi@2025 | dtdo.shimla@himachaltourism.gov.in
-- Dealing Assistant | Sirmaur (Nahan) | 7800001014 | da_sirmaur | dasir@2025 | da.sirmaur@himachaltourism.gov.in
-- District Tourism Officer | Sirmaur (Nahan) | 7900001014 | dtdo_sirmaur | dtdosir@2025 | dtdo.sirmaur@himachaltourism.gov.in
-- Dealing Assistant | Solan Division | 7800001015 | da_solan | dasol@2025 | da.solan@himachaltourism.gov.in
-- District Tourism Officer | Solan Division | 7900001015 | dtdo_solan | dtdosol@2025 | dtdo.solan@himachaltourism.gov.in

BEGIN;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001001', 'da_chamba', 'Anjali Thakur', 'dealing_assistant', 'Chamba HQ', 'da.chamba@himachaltourism.gov.in', '$2b$10$fVc1/gaolzB.jHoZnq0Mxu9siUl.xmmKXkg0Nxz3MWts.ouVRWdR2', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001001', 'dtdo_chamba', 'Rakesh Mahajan', 'district_tourism_officer', 'Chamba HQ', 'dtdo.chamba@himachaltourism.gov.in', '$2b$10$YasLfwhCgzqmFU7LKb7AS.uQEMunHs1Yu90U/1gCq5SUR5bHyB4hK', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001002', 'da_bharmour', 'Kunal Rana', 'dealing_assistant', 'Bharmour Sub-Division', 'da.bharmour@himachaltourism.gov.in', '$2b$10$IQnFhTOFmIP0oYcVMExPa.sdz0YJLvz06AuRlMbRH.8egJrxIpMA2', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001002', 'dtdo_bharmour', 'Meera Chauhan', 'district_tourism_officer', 'Bharmour Sub-Division', 'dtdo.bharmour@himachaltourism.gov.in', '$2b$10$UUpSRhyPZbkGjBzYwC8NbOkuyZckMWk4bCtzyWmdlFvZ8gGlPn6Re', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001003', 'da_shimla_hq', 'Namita Sood', 'dealing_assistant', 'Shimla HQ (AC Tourism)', 'da.shimla-hq@himachaltourism.gov.in', '$2b$10$pvAaRvLBgggEMY/leUdfl.3y8aH57vhCVsE6TQ6kprjSShmTCzNgO', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001003', 'dtdo_shimla_hq', 'Lokesh Sharma', 'district_tourism_officer', 'Shimla HQ (AC Tourism)', 'dtdo.shimla-hq@himachaltourism.gov.in', '$2b$10$U7DrGLHTKzlUSFoEYMEKR.oll.GdGmz2tedS16YtiAqpcGfBGPqfy', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001004', 'da_hamirpur', 'Pooja Verma', 'dealing_assistant', 'Hamirpur (serving Una)', 'da.hamirpur@himachaltourism.gov.in', '$2b$10$QdgNlelovMX6uyY31qMksO0vnWFuB5v/aaEI1nCGzRRYFyXOL6kDi', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001004', 'dtdo_hamirpur', 'Vikas Dogra', 'district_tourism_officer', 'Hamirpur (serving Una)', 'dtdo.hamirpur@himachaltourism.gov.in', '$2b$10$JmuNcy4SmR.sM/fBwIwW1.D2uAprZ7zWEehOEG.JUdZF7m7hK5EZu', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001005', 'da_kullu_manali', 'Sandeep Negi', 'dealing_assistant', 'Kullu (Bhuntar/Manali)', 'da.kullu-manali@himachaltourism.gov.in', '$2b$10$UWy3dhBypbLbHfgsV2ubrOX.7R.Rk8xffD1/ETIEz/VVoROzMfnKC', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001005', 'dtdo_kullu_manali', 'Ishita Kapoor', 'district_tourism_officer', 'Kullu (Bhuntar/Manali)', 'dtdo.kullu-manali@himachaltourism.gov.in', '$2b$10$J7lGXYjufXiiLIMD26p77..5EermEIUCEfURCJpL1yK0RP/bbmBUa', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001006', 'da_kullu_dhalpur', 'Divya Awasthi', 'dealing_assistant', 'Kullu Dhalpur', 'da.kullu-dhalpur@himachaltourism.gov.in', '$2b$10$iZ1fwGgPDK4qXDH12VtiGeUJE/L8pvajEFGICy5JA031kI0LVcML.', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001006', 'dtdo_kullu_dhalpur', 'Nitin Chaundal', 'district_tourism_officer', 'Kullu Dhalpur', 'dtdo.kullu-dhalpur@himachaltourism.gov.in', '$2b$10$8T7FxOD1wxS8yz0ERTlyaebRX7riZgMHjVTo5EHSlmUtopOtTb/TK', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001007', 'da_dharamsala', 'Rahul Kashyap', 'dealing_assistant', 'Dharamsala (Kangra)', 'da.dharamsala@himachaltourism.gov.in', '$2b$10$wgyPRm5sXw.wF9t1YFYHwe/dQy4NtXzX0qjJrOFTHiobV787QSUuG', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001007', 'dtdo_dharamsala', 'Shreya Mehta', 'district_tourism_officer', 'Dharamsala (Kangra)', 'dtdo.dharamsala@himachaltourism.gov.in', '$2b$10$.IQyuDI.Ijbf3btg96rX5.29Ly.zCDVtg7QnDf6VYsdi0rHBk8pcK', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001008', 'da_kinnaur', 'Tanvi Bisht', 'dealing_assistant', 'Kinnaur (Reckong Peo)', 'da.kinnaur@himachaltourism.gov.in', '$2b$10$uBfbt5THKDLusNGZtCbTnuzYRO/j2Awll0fGv.QrDJGqPNEErjRUu', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001008', 'dtdo_kinnaur', 'Arjun Negi', 'district_tourism_officer', 'Kinnaur (Reckong Peo)', 'dtdo.kinnaur@himachaltourism.gov.in', '$2b$10$r9QeJrInJ/NkY/5JN.kOmuGXk3pg1HbCT.C.qXib9ghruglAgQ0Si', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001009', 'da_kaza', 'Bharat Rawat', 'dealing_assistant', 'Kaza (Spiti ITDP)', 'da.kaza@himachaltourism.gov.in', '$2b$10$.ws6Vhj999v29JJjiTBwQ.yI9JR89gXsENTTVV3/hb4XmizSUKHQ6', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001009', 'dtdo_kaza', 'Karuna Lhamu', 'district_tourism_officer', 'Kaza (Spiti ITDP)', 'dtdo.kaza@himachaltourism.gov.in', '$2b$10$JGdSlLQt8GHV.N.9LQUNSO8XAYWRvjxOjacVysWoe/R2nqQ/Puswi', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001010', 'da_lahaul', 'Sneha Dorje', 'dealing_assistant', 'Lahaul (Keylong)', 'da.lahaul@himachaltourism.gov.in', '$2b$10$bCCyKzMZGQ7RwPDH2wgyXuUt.yAe0l.wT4rwJodflhQW5jl6hRir6', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001010', 'dtdo_lahaul', 'Mohit Bodh', 'district_tourism_officer', 'Lahaul (Keylong)', 'dtdo.lahaul@himachaltourism.gov.in', '$2b$10$ZxqxKT.Ek806FLBtA8u10.rweu7G8Xbo3.ohgSyZtpInSeEKzpm2C', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001011', 'da_mandi', 'Abhishek Vaidya', 'dealing_assistant', 'Mandi Division', 'da.mandi@himachaltourism.gov.in', '$2b$10$TT.wG8KpBt/QH/GmrQHE.OJ0bVdCwD2l/M2uZ7gA/cYL4WxksRSui', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001011', 'dtdo_mandi', 'Ritu Sharma', 'district_tourism_officer', 'Mandi Division', 'dtdo.mandi@himachaltourism.gov.in', '$2b$10$ilJMMzLjsNRaaiYiqAUM9ucjj9NaftwIXwlgJGvBajwnUzL9jRRUe', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001012', 'da_pangi', 'Jyoti Chauhan', 'dealing_assistant', 'Pangi (ITDP)', 'da.pangi@himachaltourism.gov.in', '$2b$10$CLOLyLsXKedmirkm1LF.FOoIP6UbyrgpBtV9XMEPjZF9AxxTmJ6.W', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001012', 'dtdo_pangi', 'Deepak Thakur', 'district_tourism_officer', 'Pangi (ITDP)', 'dtdo.pangi@himachaltourism.gov.in', '$2b$10$g2/uI458llTpK37qg5SbL..YnSjPcMkihAQW8I8cgGh/PkSkorVp.', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001013', 'da_shimla', 'Varun Kapila', 'dealing_assistant', 'Shimla Division', 'da.shimla@himachaltourism.gov.in', '$2b$10$9t0EgiSyWbQVlByGS.EFdOtyuW7jQzne8TIvZ2KAKyxvIYp2rexD6', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001013', 'dtdo_shimla', 'Neha Bhandari', 'district_tourism_officer', 'Shimla Division', 'dtdo.shimla@himachaltourism.gov.in', '$2b$10$YJxjOIhJcgbbNbqiwePsL.5yC7FFsqcPHkyDiHqKttaTyY8S0/0sS', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001014', 'da_sirmaur', 'Reena Gusain', 'dealing_assistant', 'Sirmaur (Nahan)', 'da.sirmaur@himachaltourism.gov.in', '$2b$10$yMPPLhpQzo7mv36H8ghf4OLXHqxKJNoUSGZcphc1TUckdNPRg98Eu', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001014', 'dtdo_sirmaur', 'Amit Chauhan', 'district_tourism_officer', 'Sirmaur (Nahan)', 'dtdo.sirmaur@himachaltourism.gov.in', '$2b$10$xKP4zG3PzlfRJXvBcUowMubwayhPSqwn.asTEqmkYYCWRiuAeDZzK', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7800001015', 'da_solan', 'Karan Pathania', 'dealing_assistant', 'Solan Division', 'da.solan@himachaltourism.gov.in', '$2b$10$fI9L/7p/7HZg278a8BoVeebMt2nw8hfMHBBEENppzDa86Rq2gpF0e', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, role, district, email, password, is_active) VALUES ('7900001015', 'dtdo_solan', 'Ishika Verma', 'district_tourism_officer', 'Solan Division', 'dtdo.solan@himachaltourism.gov.in', '$2b$10$5Y3CJvD0Uk9LLIRywKjuAuCBjOl1GXvy7S.2PM97nEhMEgtZBpq2y', true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
COMMIT;