-- District staff default credentials (generated from seed_data/district-staff-accounts.csv)
-- This version uses generic DA/DTDO names so onboarding knows they are placeholders.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

BEGIN;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001001', 'da_chamba', 'DA Chamba', 'DA', 'Chamba', 'dealing_assistant', 'Chamba HQ', 'da.chamba@himachaltourism.gov.in', crypt('dacha@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001001', 'dtdo_chamba', 'DTDO Chamba', 'DTDO', 'Chamba', 'district_tourism_officer', 'Chamba HQ', 'dtdo.chamba@himachaltourism.gov.in', crypt('dtdocha@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001002', 'da_bharmour', 'DA Bharmour', 'DA', 'Bharmour', 'dealing_assistant', 'Bharmour Sub-Division', 'da.bharmour@himachaltourism.gov.in', crypt('dabha@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001002', 'dtdo_bharmour', 'DTDO Bharmour', 'DTDO', 'Bharmour', 'district_tourism_officer', 'Bharmour Sub-Division', 'dtdo.bharmour@himachaltourism.gov.in', crypt('dtdobha@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001003', 'da_shimla_hq', 'DA Shimla HQ', 'DA', 'Shimla HQ', 'dealing_assistant', 'Shimla HQ (AC Tourism)', 'da.shimla-hq@himachaltourism.gov.in', crypt('dashi@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001003', 'dtdo_shimla_hq', 'DTDO Shimla HQ', 'DTDO', 'Shimla HQ', 'district_tourism_officer', 'Shimla HQ (AC Tourism)', 'dtdo.shimla-hq@himachaltourism.gov.in', crypt('dtdoshi@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001004', 'da_hamirpur', 'DA Hamirpur', 'DA', 'Hamirpur', 'dealing_assistant', 'Hamirpur (serving Una)', 'da.hamirpur@himachaltourism.gov.in', crypt('daham@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001004', 'dtdo_hamirpur', 'DTDO Hamirpur', 'DTDO', 'Hamirpur', 'district_tourism_officer', 'Hamirpur (serving Una)', 'dtdo.hamirpur@himachaltourism.gov.in', crypt('dtdoham@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001005', 'da_kullu_manali', 'DA Kullu Manali', 'DA', 'Kullu Manali', 'dealing_assistant', 'Kullu (Bhuntar/Manali)', 'da.kullu-manali@himachaltourism.gov.in', crypt('dakul@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001005', 'dtdo_kullu_manali', 'DTDO Kullu Manali', 'DTDO', 'Kullu Manali', 'district_tourism_officer', 'Kullu (Bhuntar/Manali)', 'dtdo.kullu-manali@himachaltourism.gov.in', crypt('dtdokul@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001006', 'da_kullu_dhalpur', 'DA Kullu Dhalpur', 'DA', 'Kullu Dhalpur', 'dealing_assistant', 'Kullu Dhalpur', 'da.kullu-dhalpur@himachaltourism.gov.in', crypt('dakul@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001006', 'dtdo_kullu_dhalpur', 'DTDO Kullu Dhalpur', 'DTDO', 'Kullu Dhalpur', 'district_tourism_officer', 'Kullu Dhalpur', 'dtdo.kullu-dhalpur@himachaltourism.gov.in', crypt('dtdokul@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001007', 'da_dharamsala', 'DA Dharamsala', 'DA', 'Dharamsala', 'dealing_assistant', 'Dharamsala (Kangra)', 'da.dharamsala@himachaltourism.gov.in', crypt('dadha@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001007', 'dtdo_dharamsala', 'DTDO Dharamsala', 'DTDO', 'Dharamsala', 'district_tourism_officer', 'Dharamsala (Kangra)', 'dtdo.dharamsala@himachaltourism.gov.in', crypt('dtdodha@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001008', 'da_kinnaur', 'DA Kinnaur', 'DA', 'Kinnaur', 'dealing_assistant', 'Kinnaur (Reckong Peo)', 'da.kinnaur@himachaltourism.gov.in', crypt('dakin@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001008', 'dtdo_kinnaur', 'DTDO Kinnaur', 'DTDO', 'Kinnaur', 'district_tourism_officer', 'Kinnaur (Reckong Peo)', 'dtdo.kinnaur@himachaltourism.gov.in', crypt('dtdokin@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001009', 'da_kaza', 'DA Kaza', 'DA', 'Kaza', 'dealing_assistant', 'Kaza (Spiti ITDP)', 'da.kaza@himachaltourism.gov.in', crypt('dakaz@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001009', 'dtdo_kaza', 'DTDO Kaza', 'DTDO', 'Kaza', 'district_tourism_officer', 'Kaza (Spiti ITDP)', 'dtdo.kaza@himachaltourism.gov.in', crypt('dtdokaz@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001010', 'da_lahaul', 'DA Lahaul', 'DA', 'Lahaul', 'dealing_assistant', 'Lahaul (Keylong)', 'da.lahaul@himachaltourism.gov.in', crypt('dalah@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001010', 'dtdo_lahaul', 'DTDO Lahaul', 'DTDO', 'Lahaul', 'district_tourism_officer', 'Lahaul (Keylong)', 'dtdo.lahaul@himachaltourism.gov.in', crypt('dtdolah@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001011', 'da_mandi', 'DA Mandi', 'DA', 'Mandi', 'dealing_assistant', 'Mandi Division', 'da.mandi@himachaltourism.gov.in', crypt('daman@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001011', 'dtdo_mandi', 'DTDO Mandi', 'DTDO', 'Mandi', 'district_tourism_officer', 'Mandi Division', 'dtdo.mandi@himachaltourism.gov.in', crypt('dtdoman@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001012', 'da_pangi', 'DA Pangi', 'DA', 'Pangi', 'dealing_assistant', 'Pangi (ITDP)', 'da.pangi@himachaltourism.gov.in', crypt('dapan@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001012', 'dtdo_pangi', 'DTDO Pangi', 'DTDO', 'Pangi', 'district_tourism_officer', 'Pangi (ITDP)', 'dtdo.pangi@himachaltourism.gov.in', crypt('dtdopan@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001013', 'da_shimla', 'DA Shimla', 'DA', 'Shimla', 'dealing_assistant', 'Shimla Division', 'da.shimla@himachaltourism.gov.in', crypt('dashi@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001013', 'dtdo_shimla', 'DTDO Shimla', 'DTDO', 'Shimla', 'district_tourism_officer', 'Shimla Division', 'dtdo.shimla@himachaltourism.gov.in', crypt('dtdoshi@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001014', 'da_sirmaur', 'DA Sirmaur', 'DA', 'Sirmaur', 'dealing_assistant', 'Sirmaur (Nahan)', 'da.sirmaur@himachaltourism.gov.in', crypt('dasir@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001014', 'dtdo_sirmaur', 'DTDO Sirmaur', 'DTDO', 'Sirmaur', 'district_tourism_officer', 'Sirmaur (Nahan)', 'dtdo.sirmaur@himachaltourism.gov.in', crypt('dtdosir@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7800001015', 'da_solan', 'DA Solan', 'DA', 'Solan', 'dealing_assistant', 'Solan Division', 'da.solan@himachaltourism.gov.in', crypt('dasol@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
INSERT INTO users (mobile, username, full_name, first_name, last_name, role, district, email, password, is_active) VALUES ('7900001015', 'dtdo_solan', 'DTDO Solan', 'DTDO', 'Solan', 'district_tourism_officer', 'Solan Division', 'dtdo.solan@himachaltourism.gov.in', crypt('dtdosol@2025', gen_salt('bf')), true)
ON CONFLICT (mobile) DO UPDATE SET username = EXCLUDED.username, full_name = EXCLUDED.full_name, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name, role = EXCLUDED.role, district = EXCLUDED.district, email = EXCLUDED.email, password = EXCLUDED.password, is_active = true;
COMMIT;
